apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-keycloak
spec:
  type: oci
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 25.2.0
      sourceRef:
        kind: HelmRepository
        name: don-auth-repo-keycloak
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      registry: docker.io
      repository: keycloak/keycloak
      tag: "26.3.0"
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
      debug: false
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
    args:
      - "--import-realm"
      - "--features=scripts"
    enableDefaultInitContainers: false
    podSecurityContext:
      enabled: true
      fsGroup: 0
    containerSecurityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 0
      runAsNonRoot: true
      readOnlyRootFilesystem: false

    proxyHeaders: forwarded
    replicaCount: 1
    production: false
    auth:
      adminUser: don
      existingSecret: don-auth-keycloak-login-secret
    postgresql:
      enabled: false
      auth:
        password: ignored-but-required

    externalDatabase:
      password: ignored-but-required
      existingSecret: don-auth-keycloak-login-secret
      existingSecretHostKey: db-host
      existingSecretUserKey: db-user
      existingSecretDatabaseKey: db-name
      existingSecretPasswordKey: db-password

    extraEnvVars:
      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: don-auth-keycloak-login-secret
            key: admin-password
      - name: KC_DB
        value: postgres
      - name: KC_DB_URL_HOST
        valueFrom:
          secretKeyRef:
            name: don-auth-keycloak-login-secret
            key: db-host
      - name: KC_DB_URL_DATABASE
        valueFrom:
          secretKeyRef:
            name: don-auth-keycloak-login-secret
            key: db-name
      - name: KC_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: don-auth-keycloak-login-secret
            key: db-user
      - name: KC_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: don-auth-keycloak-login-secret
            key: db-password
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_PROXY_HEADERS
        value: forwarded
      - name: KC_DB_URL_PROPERTIES
        value: "?sslmode=require"
      - name: KC_DB_SCHEMA
        value: don_auth
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hostname: set-in-overlay
      extraTls:
        - hosts:
            - set-in-overlay
          secretName: auth-tls
    service:
      type: ClusterIP
    podAnnotations: {}
    podLabels: {}
    extraVolumes:
      - name: realm-config
        configMap:
          name: don-auth-keycloak-realm-config
    extraVolumeMounts:
      - name: empty-dir
        mountPath: /opt/keycloak/data
        subPath: keycloak-data-dir
      - name: realm-config
        mountPath: /opt/keycloak/data/import
        readOnly: true
