version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/apps/api/base/apisix"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/apps/api/base/opa"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/apps/auth/base"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 5
