apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-route.yaml
  - oss-db.yaml
  - oss-secret.yaml
  - register-site-secret.yaml
  - don-crawler-secret.yaml
  - piwik-secret.yaml
namespace: tn-don-oss-prod
namePrefix: don-oss-
labels:
  - pairs:
      app.kubernetes.io/part-of: oss
    includeSelectors: false
    includeTemplates: true
images:
  - name: don-oss-register
    newName: ghcr.io/developer-overheid-nl/don-oss-register
    newTag: 481b2c4309badd9d07989f0343b4992f84432ffd
  - name: don-register-oss-site
    newName: ghcr.io/developer-overheid-nl/don-register-oss-site
    newTag: 721dd0d7a5e6bca2be8bf429a81de86e71cb3872
  - name: don-crawler
    newName: ghcr.io/developer-overheid-nl/don-crawler
    newTag: afb6367ade15157c25c5e8f5fd4c9ecf516b0d23
patches:
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: oss.developer.overheid.nl
