apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-route.yaml
  - oss-db.yaml
  - oss-secret.yaml
  - register-site-secret.yaml
  - don-crawler-secret.yaml
  - piwik-secret.yaml
namespace: tn-don-oss-prod
namePrefix: don-oss-
labels:
  - pairs:
      app.kubernetes.io/part-of: oss
    includeSelectors: false
    includeTemplates: true
images:
  - name: don-oss-register
    newName: ghcr.io/developer-overheid-nl/don-oss-register
    newTag: a4bb3a01585445f2f6a64d236641d64bbee1a0bf
  - name: don-register-oss-site
    newName: ghcr.io/developer-overheid-nl/don-register-oss-site
    newTag: 6c89d60760f4671e1922f099475fa2b1ba34b8d0
  - name: don-crawler
    newName: ghcr.io/developer-overheid-nl/don-crawler
    newTag: afb6367ade15157c25c5e8f5fd4c9ecf516b0d23
patches:
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: oss.developer.overheid.nl
