apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-route.yaml
  - oss-db.yaml
  - oss-secret.yaml
  - register-site-secret.yaml
  - don-crawler-secret.yaml
  - piwik-secret.yaml
namespace: tn-don-oss-prod
namePrefix: don-oss-
labels:
  - pairs:
      app.kubernetes.io/part-of: oss
    includeSelectors: false
    includeTemplates: true
images:
  - name: don-oss-register
    newName: ghcr.io/developer-overheid-nl/don-oss-register
    newTag: 2ccf0e41861835daf9bc4b4f610c624c41a013cc
  - name: don-register-oss-site
    newName: ghcr.io/developer-overheid-nl/don-register-oss-site
    newTag: 79f06d7c30d2c28c6db18fda8d5bdbf223278372
  - name: don-crawler
    newName: ghcr.io/developer-overheid-nl/don-crawler
    newTag: 1bbd572eecd66ba2fe7632be03d64060e10c7ebf
patches:
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: oss.developer.overheid.nl
