apiVersion: v1
data:
    ENABLE_TYPESENSE: ENC[AES256_GCM,data:RQjxbG4Qg04=,iv:K+yKM2qi2LbZhDo6Ws8yL1CaLKpnYO37t+VP3eGmfDE=,tag:DuJD/3toTyhNpM9kbPUDFw==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:bdfrk2yytSoGRQ15ZozQaHuZjTh9+H5bLJIm/ArT/grgF0h4NXMogL5RQVw=,iv:O5JaJaYQsWPY1vAmtaogka77YfDFlLYzWPwnWKy8SXA=,tag:tFKM/rHPXCzn9giOsJjhIg==,type:str]
    TYPESENSE_COLLECTION: ENC[AES256_GCM,data:fbA+gMzEw9gt3ngn+bw4aQ==,iv:uE1XqIbwO/A8lf9PwJi3U01Z7ku11+AKjuSVSLREE1s=,tag:voR2VbL4U1+m+F/uId2N0g==,type:str]
    TYPESENSE_ENDPOINT: ENC[AES256_GCM,data:XA8sQb6cYQa0Iow/4te6nhu8JzEodg8Enncyh2zJxckkuR4BL94BNLkC0fHIxJ7H,iv:fFnHUpqv3kC37FiF3mQXkUat1WwL0XcrUhTznFBGsJc=,tag:BwJ2+05v38ZmtybaaBJq6A==,type:str]
kind: Secret
metadata:
    name: oss-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SWR5YktMTGNWeVVNL0lQ
            dUdIaXN3TkFUcVRwcUJEZStMd291aVNVUkg0CnRoRDAvckx0RDQvODNYaklIM1hs
            Y3VSWisxamZra05QQkZzRVNyV2gwRncKLS0tIGpHNk5UL3JqaWVpZzcyNGdmS1NI
            bXN0blBVUEtxbkZuK3cwQ0g2b1hGMHcKRX5dVLYKVac/2tx65PUpxGJTIhOaUtTL
            sklZrimj5lUOFZ7YW9YTKuPnnypxMiuDEXRbcenYsJis8L7QmZhG8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T10:57:07Z"
    mac: ENC[AES256_GCM,data:zWtlnXZJ077wnq5tGbX7zEB7/rKjtf3I5QhWDM6ZP1pYIsDJQDLfdN9o0OTogFGKdvC9fhtV5liW3AFVGPWyWfxqDON9cLCUzc8/9IwamLe0phebS9NJ8AlUA60plxDQlNaBJUIOqtojChxLc0uwZPpAEMxqhK//7/4N6JrOX3M=,iv:bSGtRNR6f4MW1wT7ylcA5oK6B2ar+vlBcncEkjFdNmE=,tag:R12/dPFkegw8rj9JJ2fsKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
