apiVersion: v1
data:
    API_ENDPOINT: ENC[AES256_GCM,data:SnNjKmPO/gbpJMwwfA1hLw==,iv:2znBEDIBqDdCdAMxB9B3xo+KV1roTPrlvW442Yy4X5A=,tag:+4nhWtH1C4iMXj6iqLP6HA==,type:str]
    API_URL: ENC[AES256_GCM,data:HRvlH13Qab97SBCw+TWFQCOHc9hMAmSF00l0k+WVkqBewBVaSkYXuxZh7PQ=,iv:MB23CTldH48K+nxXJ+ojYalCy6AetMjyL75r+AXU8YM=,tag:ptsbRTenAbKvodacKsoYNg==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:Q/C6pKw+0xBoGou2CNBsmSKus8w7XxSHTV1qDNthaj8o3K+kd07VF28stf9nc2W1,iv:g9+blYeQyHK3m4tMTm7Twh6dzinA+ykfXvOT1IMggxE=,tag:sUFZjvgiabqBH2exDhbT4g==,type:str]
kind: Secret
metadata:
    name: register-site-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSTk2NTgydFhKSnJJMUhL
            bjd3RkRlVUgrZXkrYnRTbzg2MVNIM0Qzc1Q4CnhHaWluQTUrc2V5SDYrd0YvN29Y
            TGhFRFlERHZ0UHZFOHBlMHQySXZWTEkKLS0tIDJISER3UC91MFp6WHpVS2E3a0Jw
            ZUlkYzlCcEZvQllza2Q0SmZkZHVjK0EKX4ZF83ana9ncuagU4lPoBfAuzYSLsCVL
            s/Is3diWKHuArZIxsNFv/pj5mRdyBcTAlaQ/U0CXEH6nftQPxHYkfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T10:57:07Z"
    mac: ENC[AES256_GCM,data:PHaEiLJ78UzZErhSEkN5K2WA7uH1JAGtffxnBSAENxWEYpdSd65/EoyrrC35piHhh8p2aBBpJnqT0YjilrVKzUHU07/CnmjFkX0U84wOOL3Vfgc9m0tC2zJ11GpvaERJh0/syLvblT3khw+CGBHbcsmDmiP/BAbhW8udZvSUnzA=,iv:fIK/dPgRBdZ9sODGMkynTMZmqKSUTKIzS5h2pfoMRps=,tag:Tm2qCG5WR79+PchUjsmjfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
