apiVersion: v1
data:
    value: ENC[AES256_GCM,data:9RD2RtF/9QBnPairmG8Mf73dyqgtPbyc4c4OvKQuDylWg545,iv:RaBw4x+GeAhTLfZYPXAd+fK0QFogz63pt6T3pQ2WBWE=,tag:R4v7HRCuvlwrTfavireICQ==,type:str]
kind: Secret
metadata:
    name: api-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16g3k56fseufjxsh3pmt07cg7llesz2crzaw6nq7l49j9gtrv24jqu4epuk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL2NuVTFYN3VrQWhxVDBH
            RnJCaVR3TWtldW5uT2NQcHpGWURLWnBMU0ZVCnpjUVNuVjBkZkFjMzUvZDNRR2NR
            MjFFd05LZmdiRG0zU2ZGZVRNVGhydFUKLS0tIFdLWWxvVVc2YlFPRUJRRmJyT0Qw
            KzNJczdDOGVHWEsxQ21ha0h0SGZSZjgKn410BkGhumZwje8LMVm2BYgmIdNhJuBM
            drTZkM07Pp2XikRjOv10sPltLfqLo/m5xff+2R+6sbTyZDQ0y4G29A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T10:57:07Z"
    mac: ENC[AES256_GCM,data:m7O6Q+5+vHWI1Na4tMn7A0lgBSk07mOoiWyJPvzwwwQbbzCH9y/NTRk+5sOQw7m2OGv07F6l0bHVoRxzQGEFCW1AuN8f21m+xZWvECrGFar/SeWpIRqyksS3jg6ytS7BnZjNJ9yNAvV6GztgE/n540hlutRBaFqXhqMWsAkyr9Q=,iv:J+JT4jRzfuNCkIxeoG6HGWA+MrcJx2v4f1Tf/IM9D7M=,tag:QKyd5c5tUrvxgV9YaarVLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
