apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - http-route.yaml
  - keycloak-secret.yaml
  - keycloak-realm-config.yaml

namespace: tn-don-auth-prod
namePrefix: don-auth-

commonLabels:
  app: auth

patches:
  - target:
      kind: HelmRelease
      name: keycloak
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 1
      - op: replace
        path: /spec/values/production
        value: true
      - op: replace
        path: /spec/values/externalDatabase/host
        value: don-db-postgres-rw.tn-don-db-prod
      - op: replace
        path: /spec/values/ingress/enabled
        value: false
      - op: replace
        path: /spec/values/proxyHeaders
        value: xforwarded
      - op: replace
        path: /spec/values/extraEnvVars/8/value
        value: xforwarded
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: auth.developer.overheid.nl
