apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-apisix
spec:
  interval: 5m
  url: https://apache.github.io/apisix-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apisix
spec:
  interval: 5m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  chart:
    spec:
      chart: apisix
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: don-api-repo-apisix
  values:
    image:
      repository: apache/apisix
      tag: 3.17.0-ubuntu
    ingress-controller:
      enabled: false
      config:
        disableGatewayAPI: true
      gatewayProxy:
        createDefault: true
        provider:
          controlPlane:
            service:
              name: don-api-apisix-admin
              port: 9180
            auth:
              type: AdminKey
              adminKey:
                valueFrom:
                  secretKeyRef:
                    name: don-api-apisix
                    key: admin
    etcd:
      preUpgradeJob:
        enabled: false
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: set-in-overlay
          paths:
            - /
      tls:
        - hosts:
            - set-in-overlays
          secretName: api-tls
    apisix:
      nginx:
        customLuaSharedDicts:
          - name: limit-count
            size: 50m
      plugins:
        - opa
        - limit-count
        - cors
        - proxy-rewrite
        - openid-connect
      admin:
        enable_admin_ui: true
        allow:
          ipList:
            - 0.0.0.0/0
        credentials:
          secretName: don-api-apisix
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: set-in-overlay
              paths:
                - /
          tls:
            - hosts:
                - set-in-overlay
              secretName: api-admin-tls
