apiVersion: v1
kind: Secret
metadata:
  name: oss-secret
type: Opaque
stringData:
  ENABLE_TYPESENSE: "false"
  TYPESENSE_API_KEY: "changeme-typesense-api-key"
  TYPESENSE_COLLECTION: "oss_register"
  TYPESENSE_ENDPOINT: "http://don-search-svc.tn-don-search.svc.cluster.local:8108"
