apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: tn-don-static
namePrefix: don-static-

commonLabels:
  app: static

images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-static
    newTag: 08df8630e31bf46a2dafb8da89f8c8e113835606

patches:
  - target:
      kind: Ingress
      name: don-static-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: static.developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: static.developer.overheid.nl
  - target:
      kind: Deployment
      name: don-static-dpl
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
