apiVersion: v1
kind: Secret
metadata:
    name: s3-db-backups-creds
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:fuCKd6SzO6oByHJdMtzWNeoigY/OCmkvN1E=,iv:/8drv/tJFtzUjz/x/kT0IJc87QuXofmW0QEESN6DHTY=,tag:QikfF7S/yF+S74hq8QUPfg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:XkbZJnL3o1wLw4Vr3dk1mS4q40kjtoMoNcnuwKUZki6XR4nHaGke+imPIWnjEt6k/JnmqNAXbOfgl71f0h01qQ==,iv:3Xabuq6HFH8uzwt7AEMxMSfr3aws7lVJKFPg20T48AM=,tag:N/On62ZAjs6/jMiku46RJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcXR6UGcxVnJpYWN2aW1X
            L0NoV0VQOXB0cDdzNjRMaVZRVmg2TDZHNlZVCmpYQmlDMncvMlJPMG9YdmxLVVlk
            UGpaVGFrcU4yNFExNUZyU2hzYkcyZXMKLS0tIExJaTFMelY1L0NhMEt3Vy9OL0RX
            bFVwd3VRS3VPaENzSDJwbkRzNjdJbmMKKkTSieyzattySU3qSMmwCkvlqAJaI3zi
            1lVv3/qSqGtkK02i3zftql2Kfz7r4ostE0ozbZSqfqzrkT753cfa/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jpw5maslwqs6av7qxj62qc8gz2g496ul0v0kfz3lzsucfqr45e8qkyx8fd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T07:36:17Z"
    mac: ENC[AES256_GCM,data:INz5J1QKf4eukc2xB0z4TaXDqjZHdJGvcqErUaVBSrnmUyrRRdBb8IkV2lHNQO94awnKceGpxsP68UPSf8TrYdb7cLdHEL/06uEdqFuh/VDR4cDFkRES3AoYp7cd0kgRxqdFfzNtnCVlAQaKUvobBiQUPReEah9OQRXBCCXLvuE=,iv:j0u1lMoEYBHE7pImlcG6k16oU5jgQHXFUNRX0bQq1TY=,tag:RefyjSlwO3m00rNNpVVLzQ==,type:str]
    version: 3.13.0
