apiVersion: v1
kind: Service
metadata:
  labels:
    app: source-meta
  name: source-meta-svc
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: http
  selector:
    app: source-meta
