apiVersion: v1
data:
    API_ENDPOINT: ENC[AES256_GCM,data:EthqfCcb+x3g2EaAJJO2AUV6dEgMY5P8hUEPUNee5hEQBMduSfy/6gW0K5Z/cI7wvg4KVTwC12M=,iv:22N0+yXPKq5I2Mo4oAh0wrFsz/hmSmTWIAiyXFJqMS8=,tag:5kGNeuG5YE/6nzUUalwKhA==,type:str]
    ENABLE_TYPESENSE: ENC[AES256_GCM,data:Pi0wK/yDCrc=,iv:roHOLBzFsuaZ7fOwJ4lnx703YgJ/QDSdkxswzhV4P9U=,tag:zWOQXvwY14tnZJ606gwxLw==,type:str]
    TOOLS_API_ENDPOINT: ENC[AES256_GCM,data:j3M5ryBFhof7RQH801kluzbIIxbL3+QEef3QvT8xXO0IAvSK+XmJBrNi2/9G5BRz8yproPDi1iRfZ9jh,iv:VQwRBTIU/VoZjfmGKBnJWXe8F2WFeiDBoipl1Mn2Wfw=,tag:3/ORU5FbP2xZdTrvsRV8Sw==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:s6DPdwILIm0lYM5SInoYegbLsPNQoCg+DJ8LjPWJlv4+wJgYXG4imT2Eq40=,iv:i3qbti4BTjBnnPys2H4VnUB9cZORzRie1wfIkHqbgCI=,tag:MVi30DT1F1mudepibFXhHA==,type:str]
    TYPESENSE_COLLECTION: ENC[AES256_GCM,data:l+23gg4/uh9GEVSpg5nN2w==,iv:uYkiA/ICSh86Ma03yvgXjFDUTlrm3PcsWeeIyn0W52c=,tag:ck1QzU/IitFJ4neX2HNfzw==,type:str]
    TYPESENSE_ENDPOINT: ENC[AES256_GCM,data:9lvli3VZ6Dxo1tH3saEbLb0Ka328bCR1HPiz7iH0llTz+AzJVMvbOrIp0qZwqTMx,iv:d8FmZQvRGPAIHjt1Sf61tYayBwVp7uizn7rGdx2W41E=,tag:cWPE44PPKzjsOYPeIMpqsw==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:W9rq+upxZm2PT1b/FjIRaQx5yks3j6GcdIUXb1Dugz5hIx9/djDYZqNEAzOwdHqc,iv:E/cE5xxTlPjCWvDrxfc5WurDLwkl/hrEmsZmKMpcZ0E=,tag:5qNuxXR1lO3chDd9m64q2g==,type:str]
kind: Secret
metadata:
    name: api-register-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySkM1Rm1JdUIxVElNblBv
            M1VyMHJ0M0VMaDk2RE5Jdzdzb0ttRERCbm1VCmo0dlBFR0tXaDJzRE1jZ1BTYVFQ
            eTFsa2s0MngyL0w5d3czQ1RwVzErQXcKLS0tIHl4NUhYSlFIeU8wempxa3B5YTVF
            VzVqeWUzMDJucjM4Yjc5RFJYUU82TjAKNRHtoeVf0BzNQOVJ+KiDLji+K5AiCkCf
            /19K7MHLBSEfHFMmHuy4Sx9XXbMyIygYT5c7479vr7VkCLAG6J0Esg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T10:57:06Z"
    mac: ENC[AES256_GCM,data:7UnlBGzfjmfyhjs5JqhEZ7AwbljJEsHrcnGls9XdTIqjlThoK6IPZUNe527TzJ7kY6Pex5iW04HHQz7JKpin00GhWHnnrNKdqgGy6t+CBbLz7cu0pZnI3ukpA0D5aYFm4cGMt4Qu28/VsVjrEPQPfLYb6DznSfimVBwV8FGUHiA=,iv:Kn6XY1ij6dDbw4vkxGqO4+Zke/VMUW76jYsTki6y9/g=,tag:lxNMTzcFjEYcpZRS0x6EjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
