apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: authenticated-rate-limit
spec:
  ingressClassName: apisix-prod
  plugins:
    - name: limit-count
      enable: true
      config:
        count: 500
        time_window: 60
        key_type: var
        key: http_x_opa_client_id
        # APISIX vereist een nieuwe groepsnaam wanneer de limit-count-configuratie wijzigt.
        group: authenticated-api-users-v2
        policy: local
        rejected_code: 429
