apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - register-site-http-route.yaml
  - apisix-http-route.yaml
  - apisix.yaml
  - register-site.yaml
  - tools-secret.yaml
  - api-register-secret.yaml
  - api-register-db.yaml
  - piwik-secret.yaml
  - opa-auth-config.yaml
  - apisix/routes/apisix-routes.yaml
namespace: tn-don-api-prod
namePrefix: don-api-
images:
  - name: don-api-register
    newName: ghcr.io/developer-overheid-nl/don-api-register
    newTag: 13519f0586e513ce8d17b87306a152ecc6f0d5af
  - name: don-register-site
    newName: ghcr.io/developer-overheid-nl/don-register-site
    newTag: 79f06d7c30d2c28c6db18fda8d5bdbf223278372
  - name: don-tools-api
    newName: ghcr.io/developer-overheid-nl/don-api-tools
    newTag: dea9f870f88ac8f5eef77b71af605e520d017a83
patches:
  - target:
      kind: HelmRelease
      name: apisix
    patch: |
      - op: add
        path: /spec/releaseName
        value: don-api-apisix-prod
      - op: add
        path: /spec/values/fullnameOverride
        value: don-api-apisix
      - op: add
        path: /spec/values/ingress-controller/config/controllerName
        value: apisix.apache.org/apisix-ingress-controller-prod
      - op: add
        path: /spec/values/ingress-controller/config/kubernetes
        value:
          ingressClass: apisix-prod
      - op: replace
        path: /spec/values/replicaCount
        value: 1
      - op: replace
        path: /spec/values/ingress/enabled
        value: false
      - op: replace
        path: /spec/values/apisix/admin/ingress/enabled
        value: false
  - target:
      kind: HTTPRoute
      name: apisix-http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: api.developer.overheid.nl
  - target:
      kind: HTTPRoute
      name: apisix-admin-http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: api-admin.developer.overheid.nl
  - target:
      kind: HTTPRoute
      name: register-site-http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: apis.developer.overheid.nl
