apiVersion: v1
data:
    admin_api_url: ENC[AES256_GCM,data:evcaOf4MHWCCENgHaa5at3DE6TD3H83+R2AgXuui8wH8h1fXIUC2E5VFeZ6YDnv5jvwqKDEoStUGbBQ5evgZ3bvc0Ek8atc8br8XPC592wo=,iv:QdEAy8jL7PZLZpyZywEo83vulyzCfOqsTuRrmI2KoFk=,tag:QJi00QFcLAmN3fRZemQmzA==,type:str]
    admin_grant_type: ENC[AES256_GCM,data:zh2K8mRpm1rSTk5cqqwat19Y4XFEkbAg,iv:MsVJ/7BoIa5aCMwp86pantqCUMUpRSZGNELnGulU7yw=,tag:nINJTPBm9SYUsz7EhrNmVw==,type:str]
    client_id: ENC[AES256_GCM,data:9F2c2j1xHIShQGrLy46JH1MWSmSCCacR,iv:9bm6puDwP3hTHghph8lggwdPPp0ipwoZhK1WvW93xX4=,tag:qbaWEmwwgIoJRiGmyEJlGQ==,type:str]
    client_secret: ENC[AES256_GCM,data:dpPlbsvrLikYEWTni+Iqsemi7LhIhrnoyr9Lw5nRO/hkQ+Rlexl73X65q4w=,iv:ATNa3HIoqMwdOnqHg6YhEJ2Gloy2jMPVlE66u2XEyz0=,tag:Z9icvehglNE5d5/9Nsgt5Q==,type:str]
    introspection_url: ENC[AES256_GCM,data:7A01q8g1CG05qw3h7rWV1zX75Iqb2g9IBPPVPTkh6HpgOsiaAD5Arl+rVZXTHcJnMVuOI7Tgo06exDSz2EqkLAZ22jnUe6g/JuKxw/D6GKVGQ8xsIThWQ2kAdUaYjxLI2ento/Dh2Vrz4wxgPkyoYJFKLIw=,iv:SEIGU+CZSrwfxpj/yt2DExN0cADWs57WSXmHMc+kEak=,tag:oRZlD3+bX7VGVkVR+5KfEw==,type:str]
    token_url: ENC[AES256_GCM,data:37odX+qkznwrtAeb59VHNZXD9QXX9wbuqiZv7w9yobURst+Jo2nGDEzvNtRjy/mtMce3BGNTAX3yu7KHsaRJ6KcHGyEsVkGYGjEOObtpoHZFj03hLPlUqRIIlt9uCPimw81VkA==,iv:ysh9jJlAzgoRd6RFCge0AD2knIDDyU6wr4ordU4yGZQ=,tag:8wT+gQCSRDxxL2FPto9h8Q==,type:str]
kind: Secret
metadata:
    name: opa-auth-config
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveTNlVDVzaTFmOW50VUlD
            MmRiTlZkZWJObTVma3FnMmhYSk1lVTFyYkVRCnZMTUVyaTYzakdJTlU0KzJqdm9o
            dm05OTZ3ZDczTUZzQnlnbkQybmdzNkUKLS0tIGNlRkJjSnl5OFZVV2M3Q3RQLzhI
            Y0RXYUpsRGNGT04ycFpKcS9walJ6VTQKQL7lxFEWuWaUpWWi3L87m18OC7gjk7JT
            xKD/qxEJOoMGKyGf4K+EGiUcJa0HRTe+J1Op+7sRi+0dSSrwcBiuuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T10:57:06Z"
    mac: ENC[AES256_GCM,data:hpiPFFzAAQLZeFvMuCBSiXGL58apoxg4YOe1ZztGXfKdN5P6drhHpzkERk0z0KSstEN98WMTXJbV77edD9WdIs4455QI1moqjiDAi/mBSCi+1PTQkbAeRg/MHYqDVK1T5/LyhCm8r+bMGWCBTLEKLyB4xVVj5tkWtdNpxtv8L3Y=,iv:JPGiUS5e4Z1slNTWyiWhNaFGSj5CbEfzax3MtS8Q1kw=,tag:8rZT16yG2QuJz+qH7h4yBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
