apiVersion: v1
data:
    ALTCHA_HMAC_KEY: ENC[AES256_GCM,data:gmNQzuMM9uFJKW5x5MmXSQkOvDQ2hwuErxa227OSlkaIMLxXsAoKD5RneSXjGloSNxwljLhL2ytmGUChZ7dJkZXJ/zDkT3GK0Cx1Wx+HZSgthxhk6XJVug==,iv:sfaWM/rPd0FcnWxDj0ixuLe8kh802m7Nt1Ol4BHdPg4=,tag:X0ZeAMQeJU1NsTQ2qHBgQw==,type:str]
    API_ENDPOINT: ENC[AES256_GCM,data:jCdRuDTbCrhA9daKkdvpnQ==,iv:CNk9IcIOwggJpBWb4/bA0GdPKcIjxp8LWVJW0ZGge3g=,tag:cZ8vypKueez6QTAwX9JWyw==,type:str]
    API_URL: ENC[AES256_GCM,data:P+l2sZC98Avku7sJlaqqssViuDxjrLVfwcbey9ZRVsWm8ZL5Ra7EPtxPM30=,iv:pn8lbGMNiScHPF7+B0WLjYFqEtXwZjXzttEhtQ7bljQ=,tag:9T6FQ/bWkfxVqCj+wvNLMg==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:IXUBGzTiDvD6YLn2VqcCM6EGKMCRHFBaDDiDowo30yNtahPpNEcVhk5J18QJMMsp,iv:AbnjL0MZoV3zHJhI3l8ozVaGSwzqCDbivI9x0voXJcQ=,tag:jmeCCDH9lamyD3XMJwNCJQ==,type:str]
    TOOLS_ENDPOINT: ENC[AES256_GCM,data:Ad2cLPFHplM=,iv:vH+aPgHQYs+BUiGS/0slR1gFLg4KrSVXUO+Zc5MMz4k=,tag:F0w3G3Kc36a7wrq4Pi8l6Q==,type:str]
kind: Secret
metadata:
    name: register-site-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdEloWjJCMVR2aWxtQ3lB
            eG80S1BLbzBpME5sV09rdDEwOXZsNVdveVNrCmtrRXBVYWEzODdvRnRhQTREWE5o
            VnlDbVJvM3JnTzNXYkd1RUxBNlNXWTQKLS0tIGpNM1RLYUpjWkM1Tlk0UWZiMkQr
            TWpoVGNsaHpaU0JOdDB4UEFkUkZiaUUKSMZUdgExdv1q41HAys0PHjehnhXkb1eZ
            VOBxPNMPo2yCftZu9MdOaTfeyup1povP13bDDIeHXm6AjJlnIwI0Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T10:57:06Z"
    mac: ENC[AES256_GCM,data:EAoYSPA9ATyFPCuQgQF3XRfXJ0SUxnAMWde2C3tMz8g3ic/4Lse/fRD+MrXLEVv+KvVT9an+7cK5DDVX8KxOha6vKQ2ZY97lYMMwjXkCR/zM1guAIrt1lSU/1JkL3Ts/l2EQZjtBC07VgZXnsSugTmCMjBdYkcwONVhxeyklCLk=,iv:10J13U9/Wmm03q938bhWQuoTb/p7VfqMVBpDThNmXIc=,tag:qV9QjKxh1wsaTLF5S7E81A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
