apiVersion: v1
data:
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:Y/HmleokEAsvFj1qx3b31DQcwjFVvrtd,iv:1WC9AlA9pVd/f28v+y0n6lXq8hHxI+ysCM4dF64MKA8=,tag:GdZa1VJM92ANqdMEJDh41Q==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yUEnXW7kdARJIuPhs/03aqZac+l8TP4XdcmLKnoLc4Ps5CyUj3dpWR2Au2s=,iv:Yks1001k8wflhYinWey+waYF6CwEKOEM0U9xpdhOj1M=,tag:6ahxEMCaDO/kI/IYdGS/Cw==,type:str]
    KEYCLOAK_BASE_URL: ENC[AES256_GCM,data:KqPWP/MybDhXJKcCKeSDFQ2/taFnKER3Tiyxh0ancUxn/OalroN/IPrB2XJTdVdf,iv:frZxvhVZKnLqN85jsbC49IaitEKpD146G0YbcIa7hAg=,tag:rkI+lwin4EsVNA/R4UW9/A==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:WRKixw==,iv:mXbENNGeXxOIrvJa5/iL6sj5xJPJS1ZCa5rmaksbL+o=,tag:J7zXgUe0MTUPexR6dYCekg==,type:str]
    PDOK_REGISTER_ENDPOINT: ENC[AES256_GCM,data:epI08X/2R4UYofgSKdHJs/doYzXJ+1JHsbjbSyymWffwvNMt39cOLe7yOTDU+euJXoWMahpcZkgX6gdXtG6IM+BMWxgWRWcS,iv:pJ/wP7Gi39e5lOaQIqpvre6YI3z46CRXsovJvh+r4e8=,tag:bqk1NzOq9ydioaSXd7pzig==,type:str]
kind: Secret
metadata:
    name: tools-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblpZQmtVOEVGYzN5cFVB
            Qjd3T0czRXRkbUVrTThZYzREZ0tZQkpwS3lBCmFxY3Jxem4ybUN2S1dlY3NLd2tF
            N3dDeFowWW9iN3hzR2RaVmpGcm9iR28KLS0tIGt3OVBWOEFwQkNkWEtsNGt4VUZM
            a1NHT3hqNitlRERzOHJvNzkwNEM0YzQKFukIJc6ldi1b+W3him9ADnHEMoGrsU5U
            QGHwBhpzmr4J/oGG1A1u8XZXtrqRJRIlSY9Lz9r3l2UzZjsygcUmMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T10:57:06Z"
    mac: ENC[AES256_GCM,data:G13eCYCtWL9YSiz7M5XP2G9Z9MmFkij9FKZjDgKY81X2tXwCvZXl39m68Qyzi+j6Kym6/feKOUYpwhI5dWx5p8kXFUeTWm+YO4JYEsibArK7x5+KFFM+Gco6P5DBG3ABCo2IpYFUDN/a34Ta02YyTOEXwUEDSVXyxUvvRwzqEnU=,iv:ViA3Q3dntPBCIpKKlS2YlB9T+dyV47kCmf7nrXmv1fY=,tag:b0vDoUZWZZybp4H1WrTBlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
