apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - http-route.yaml

namespace: tn-don-static
namePrefix: don-static-

images:
  - name: source-meta
    newName: ghcr.io/developer-overheid-nl/don-schema-register
    newTag: c90a5285f519fb30733f03e2262a72148e95d20b

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: static.k8s.orb.local
      - op: remove
        path: /spec/tls
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: static.k8s.orb.local
