apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-don-static
namePrefix: don-static-

commonLabels:
  app: static

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
