apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-route.yaml
  - piwik-secret.yaml
namespace: tn-don-frontend-prod
namePrefix: don-frontend-
commonLabels:
  app: frontend
images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-site
    newTag: 41734f30b16e2b9e3423cfc692f8f9d56c600d84
patches:
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: developer.overheid.nl
