apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-route.yaml
  - piwik-secret.yaml
namespace: tn-don-frontend-prod
namePrefix: don-frontend-
commonLabels:
  app: frontend
images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-site
    newTag: 515206410292465f94e74d6e990bc502c2b9d9fd
patches:
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: developer.overheid.nl
