apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-bitnami
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discourse
spec:
  interval: 5m
  chart:
    spec:
      chart: discourse
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: don-community-repo-bitnami
  values:
    host: set-in-overlay
    siteName: Developer Overheid
    replicaCount: 2
    image:
      debug: false
    ingress:
      enabled: true
      hostname: set-in-overlay
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    auth:
      username: admin
      email: developer.overheid@geonovum.nl
      existingSecret: don-community-discourse-admin
    postgresql:
      enabled: false
    externalDatabase:
      create: false
      host: set-in-overlay
      database: don_discourse
      user: don_discourse
      existingSecret: don-community-discourse-db
