apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-bitnami
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discourse
spec:
  interval: 10m
  chart:
    spec:
      chart: discourse
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: don-community-repo-bitnami
  values:
    ingress:
      enabled: true
      hostname: set-in-overlay
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    postgresql:
      enabled: false
    externalDatabase:
      host: set-in-overlay
      database: don_discourse
      user: don_discourse_dml
      postgresUser: don_discourse
      existingSecret: don-community-pg-discourse
      create: false
