apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-bitnami
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discourse
spec:
  interval: 10m
  chart:
    spec:
      chart: discourse
      sourceRef:
        kind: HelmRepository
        name: don-community-repo-bitnami
      version: 14.1.6
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    postgresql:
      enabled: false
    externalDatabase:
      host: rg-apps-sandbox-westeu-001-psql-1.postgres.database.azure.com
      database: don
      user: don-community-dml
      postgresUser: don-community-adm
      existingSecret: don-community-pg-secret
