apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-runix
spec:
  interval: 10m
  url: https://helm.runix.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
spec:
  interval: 10m
  chart:
    spec:
      chart: pgadmin4
      version: 1.29.0
      sourceRef:
        kind: HelmRepository
        name: don-community-repo-runix
        namespace: tn-don-community
  values:
    ingress:
      enabled: true
      hostname: set-in-overlay
      path: /pgadmin
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
